name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: athulkjose01/eq:${{ github.sha }}

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: "135.235.192.249"
        username: "azureuser"  # or Ubuntu, depending on what you chose while creating the VM
        key: ${{ secrets.VM_KEY }}
        script: |
          echo "Cleaning up old containers on port 8000..."
          containers=$(docker ps -q --filter publish=8000)
          if [ ! -z "$containers" ]; then
            docker stop $containers
            docker rm $containers
          fi

          echo "Pulling latest image..."
          docker pull athulkjose01/eq:${{ github.sha }}

          echo "Stopping existing container named eq..."
          if docker ps -a --format '{{.Names}}' | grep -q '^eq$'; then
            docker stop eq
            docker rm eq
          fi

          echo "Running new container on port 80 (since port 8000 might be blocked)..."
          docker run -d --name eq -p 80:8000 athulkjose01/eq:${{ github.sha }}

          echo "Cleaning up unused Docker resources..."
          docker system prune -af
